spring:
    application:
        name: two-factor-service
    datasource: 
        driverClassName: com.mysql.jdbc.Driver
        url: "jdbc:mysql://localhost:3306/final?autoreconnect=true"
        password: "test"
        username: "password"
server:     
  port: 8087